### ISSUE TITLE
nit: renaming utxo.account to utxo.address

### ISSUE THREAD

**Issue by SwenSchaeferjohann** [helius-labs/photon#4]
can we call the optional persistent address field of a utxo `address` instead of `account`?

we'd be using `address` in the client & program, which will then also be consistent with the naming of the uncompressed equivalent in the [new web3js](https://github.com/solana-labs/solana-web3.js/blob/master/packages/accounts/src/account.ts#L16C14-L16C21) `Account.address` type

**Comment by pmantica11** [comment]
Done!
